package oidc_cli

import (
	"context"
	"fmt"

	"github.com/coreos/go-oidc/v3/oidc"
	"golang.org/x/oauth2"
)

const (
	ScopeProfile = "profile"
	ScopePhone   = "phone"
	ScopeEmail   = "email"
)

type Config struct {
	OidcProviderURL string
	ClientID        string
	ClientSecret    string
	RedirectURL     string
	Scopes          []string
}

type ResponseTokens struct {
	AccessToken  string `json:"access_token,omitempty"`
	IDToken      string `json:"id_token,omitempty"`
	RefreshToken string `json:"refresh_token,omitempty"`

	Claims IDTokenClaims `json:"claims,omitempty"` // useful info contained in the id token

	TokenType string `json:"token_type,omitempty"`
	ExpiresAt int64  `json:"expires_at,omitempty"`
	Scope     string `json:"scope,omitempty"`
}

type IDTokenClaims struct {
	*BasicClaims

	Audience  string `json:"aud,omitempty"`     // client id
	Nounce    string `json:"nounce,omitempty"`  // ramdom generated by client
	ATHash    string `json:"at_hash,omitempty"` // access token hash - for client to validate the access token
	Subject   string `json:"sub,omitempty"`     // user id
	Role      string `json:"rol,omitempty"`     // role of user
	SessionId string `json:"sid,omitempty"`

	*UserinfoClaims
}

type BasicClaims struct {
	Issuer    string `json:"iss,omitempty"`
	IssuedAt  int64  `json:"iat,omitempty"` // issue time of token
	ExpiresAt int64  `json:"exp,omitempty"` // expire time of token
}

type UserinfoClaims struct {
	Nickname string `json:"nickname,omitempty"`
	Picture  string `json:"picture,omitempty"`
	Gender   string `json:"gender,omitempty"`

	Email         string `json:"email,omitempty"`
	EmailVerified bool   `json:"email_verified,omitempty"`
	Phone         string `json:"phone,omitempty"`
	PhoneVerified bool   `json:"phone_verified,omitempty"`
	Group         string `json:"group,omitempty"`
}

func Callback(conf Config, code string) (*ResponseTokens, error) {
	if len(conf.OidcProviderURL) == 0 {
		conf.OidcProviderURL = "https://api.bingyan.net/sso/oidc"
	}
	if conf.Scopes == nil {
		conf.Scopes = []string{oidc.ScopeOpenID, ScopeProfile, ScopePhone, ScopeEmail}
	}

	provider, err := oidc.NewProvider(context.Background(), conf.OidcProviderURL)
	if err != nil {
		return nil, err
	}

	oauth2Config := &oauth2.Config{
		ClientID:     conf.ClientID,
		ClientSecret: conf.ClientSecret,
		Endpoint:     provider.Endpoint(),
		RedirectURL:  conf.RedirectURL,
		Scopes:       conf.Scopes,
	}

	token, err := oauth2Config.Exchange(context.Background(), code)
	if err != nil {
		return nil, err
	}

	rawIDToken, ok := token.Extra("id_token").(string)
	if !ok {
		return nil, fmt.Errorf("no id_token found")
	}

	verifier := provider.Verifier(&oidc.Config{ClientID: conf.ClientID})
	idToken, err := verifier.Verify(context.Background(), rawIDToken)
	if err != nil {
		return nil, err
	}

	var claims IDTokenClaims

	if err := idToken.Claims(&claims); err != nil {
		return nil, err
	}

	return &ResponseTokens{
		AccessToken:  token.AccessToken,
		TokenType:    token.TokenType,
		IDToken:      rawIDToken,
		Scope:        token.Extra("scope").(string),
		ExpiresAt:    claims.ExpiresAt,
		RefreshToken: token.RefreshToken,
		Claims:       claims,
	}, nil
}
